services:
  - type: web
    name: crud-app-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crud-app-db
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: PORT
        value: 3000